- improveDataFiles.R
This fixes Alex's first issue from #9 
Cannot close just yet but progress
> Fix for duplicate drugs 

- data/getLatestCCLE.R
- data/initialSampleDB.R
- pgx/pgxToImprove.R
Created an update using the older sample_info.csv file compared to model.csv. On the upside, cellosaurus updated their annotations, which is nice. Closes #10
> updated sample database

- build/dockerfile.mpnst
- build/mpnst/README.md
- build/mpnst/mpnst_get_cnv.R
- build/mpnst/mpnst_get_rna.R
- build/mpnst/mpnst_get_wes.R
- build/mpnst/requirements.r
- build/mpnst/requirements.txt
- build/mpnst/synapse_NF-MPNST_samples.csv
'NF_MPNST_samples.csv' has been provided with comprehensive annotations for each improve_sample_id, akin to those in other datasets. In parallel, 'synapse_NF_MPNST_samples.csv' includes similar annotations and pairs them with compatible synapseIDs, enabling additional downloads via Rscript.
Furthermore, the 'mpsnt_get_cnv.R' script has been refined to download and merge MPNST PDX and tumor copy number variance with a focus on protein-coding genes. It utilizes the GENCODE42 gene mapping table "knowledge_based_isoform_selection_v1.3.txt" from the 2023 CPTAC Pan-cancer Cell paper by Yize Li et al., ensuring a robust and current genetic framework. Additionally, the 'genes.csv' file has been employed to translate gene symbols into entrez IDs.
The updates also encompass the 'mpsnt_get_rna.R' …
> MPNST Data Processing and Annotation

- build/cell_line/03-curves_and_drug_mapping.py
- build/cell_line/03a-drugAndResponseData.R
- build/utils/mapDrugsToPubchem.R
finally i think the drugs file doesn't disappear.
> found the bug fix!

- build/cell_line/02a-cellLineSanger.R
I can't find an issue number, but this fixes the sanger cell line data processing issue
> fixed bug for jeremy

- build/cell_line/02a-cellLineSanger.R
The download isr unning really slowly from my home wifi, so I'm going to rely on CI to ccheck the code.
> tried to fix #81

- build/cell_line/02-cellLineDepMap.R
- build/cell_line/README.md
- build/dockerfile.cptac
addresses #89 but i'm not sure it works (can't repro locally)
> Cell line bug fix

- coderdata/load/loader.py
Fixed issues #113 and #114.
Added genes file to object as desired in #117.
> Fixed bugs in package and added gene mapping

- README.md
Update the Readme to include the Data Source Reference List.
I'm going to work on the rest of the Readme before AACR, so lets wait on merging the PR until this is ready. There also may be more references added.
> Update README.md to include Data Source Reference List

- coderdata/download/downloader.py
- requirements.txt
- setup.py
Sorry for the confusion,  this should resolve the pyyaml issue.  Local git env was mixed up for me - this is now resolved.
Fixes #145
> New pyyaml fix

- .dockerignore
- build/beatAML/GetBeatAML.py
- build/beatAML/requirements.txt
- build/broad_sanger/02-broadSangerOmics.R
- build/broad_sanger/build_omics.sh
- build/docker/Dockerfile.beataml
> Docker cleanup

- build/beatAML/GetBeatAML.py
- build/utils/fit_curve.py
- candle_bmd/fit_curve.py
This works locally, I'm not sure the best way to ensure this doesn't take up too much memory on a high CPU, low mem computer (this is probably rare though).
We originally spoke about multi-threading, but multi-processing seems like a better [option](https://stackoverflow.com/questions/3044580/multiprocessing-vs-threading-python) overall .
I saw a 6x increase in speed for drug curve fitting!
Resolves #140.
> Add multi-processing to drug curve fitting

- build/broad_sanger/02-broadSangerOmics.R
- build/build_all.py
here we harmonize the copy number callls. closes #174
> added fix for copy number

- README.md
- build/mpnst/02_get_drug_data.R
This is a very small fix to the README that allows the buidl process to accomodate new users. @nkoussa can you maybe try out?
> added instructions for synapse download

- README.md
- build/beatAML/GetBeatAML.py
- build/hcmi/01-createHCMISamplesFile.py
- build/mpnst/00_sample_gen.R
- build/mpnst/01_mpnst_get_omics.R
- build/mpnst/02_get_drug_data.R
- build/utils/fit_curve.py
Fixed three issues with files including:
#181 #182 and #180
> Sample schema fix

- schema/coderdata.json
- schema/coderdata.yaml
- schema/generate_croissant.py
there are still some issues but honestly i can't figure out what's up.
> added croissant metadata generator and file

- build/utils/fit_curve.py
It turns out we already have a goodness of fit statistic, closing #198 
However, this fix force hill slope to be negative, also updated DSS code, which were not documanted!
> Fixed problem with hill slope

- build/utils/fit_curve.py
this will allow for increased range in curve fitting.
> allowed hill slope to be positive

- build/beatAML/GetBeatAML.py
- build/utils/calc_pdx_metrics.py
- build/utils/pubchem_retrieval.py
Fixes are as follows:
- Fixed OOM issue with BeatAML that resulted from casting to int.
- Added drug retry method for pubchem retrieval.
- mpnstpdx experiments and combination files are now written to tsv.
- mpnstpdx experiments and combination files now have all expected columns.
@sgosline I need help on determining what **time** and **time_unit** should be used for mpnstpdx files.
Currently treat_time is an array (from which I set the max value as time) and time_unit was previously set to "days" which is incorrect for these values.
```
trabectedin
treat_time:, [ 0.  1.  4.  6.  8. 11. 13. 15. 18. 20. 22. 25. 27. 29. 32. 34. 36. 39.
41. 43. 46. 48. 50. 53.  0.  1.  4.  6.  8. 11. 13. 15. 18. 20. 22. 25.
27. 29. 32. 34. 36. 39. 41. 43. 46. 48. 50. 53.  0.  1.  4.  6.  8. 11.
28. 13. 15. …
```
> Several Bug fixes - OOM, Drug retry, mpnst pdx fixes

- build/hcmi/02-getHCMIData.py
This aligns HCMI copy calls with the other datasets.
This addresses issue #268.
> Fix Copy Calls in HCMI

- build/README.md
- build/build_all.py
- build/docker/Dockerfile.upload
This removes all code, dependancies, and references in the build README.md to the Python package.
Python package build process and PyPI upload will now have to be run **manually** for each dataset build.
This resolves https://github.com/PNNL-CompBio/coderdata/issues/275.
> Decouples All Python Package Build/Upload steps from the Data Build/Upload process.

- coderdata/dataset.yml
Dataset descriptions could potentially use more information.
Just pulled the dataset name / descriptor from PharmacoDB for the "new datasets" where possible.
> prepare pypi release 2.0.0

- build/cptac/getCptacData.py
> CPTAC Samples file bug fixed

- build/bladderpdo/00_createBladderPDOSampleFile.py
- build/bladderpdo/01_createBladderPDOOmicsFiles.py
- build/bladderpdo/02_createBladderPDODrugsFile.py
- build/bladderpdo/03_createBladderPDOExperimentFile.py
- build/bladderpdo/CNV-segfile-annotation.R
- build/bladderpdo/build_drugs.sh
- build/bladderpdo/build_exp.sh
- build/bladderpdo/build_omics.sh
- build/bladderpdo/build_samples.sh
- build/bladderpdo/obtainGSMidLink.R
- build/bladderpdo/requirements.R
- build/bladderpdo/requirements.txt
- build/build_dataset.py
- build/docker/Dockerfile.bladderpdo
- build/docker/docker-compose.yml
Closes #265 
Final documentation still needs to be added - will add in a separate PR in the interest of time.
> Bladder PDO dataset addition

- scripts/prepare_data_for_improve.py
Small change to the improve wrapper script
> added drug exclusion to `drug_info` and `morgan fingerprint`

- build/docker/Dockerfile.upload
- schema/coderdata.yaml
Small change in how the validation scripts/files (particularly "expected_files.yaml") are added to dockerfile. This was previously always pulling from main when it should instead be branch specific for development purposes. 
This resolves #370.
**Edits:
This now also resolves #357.
> This resolves an inconsistency for validating new and old datasets

- build/beatAML/GetBeatAML.py
Mutation data now in the same format as other datasets. 
This resolves #315.
> Aligned mutation style with other datasets

- build/sarcpdo/03_createSarcPDOExperimentFile.py
> fix missing time and scale of published_auc in sarcpdo experiments file

- coderdata/download/downloader.py
md5sum check for downloaded files is implemented.
ran some basic test and it seems to be functional.
could NOT test with corrupted md5sum, but tested with "inverse logic" i.e. retry if calculated md5sum and expected md5sum match
> implemented md5sum check for downloaded files

- build/utils/fit_curve.py
Yitan pointed out issues with the curve fit and they are updated here.
> update curve fit

- build/build_all.py
- scripts/align_drug_descriptors.py
Updates:
- **New** align_drug_descriptors.py file
- **Changes** to build_all.py file 
This addresses issue #323.
> Drug descriptors are now harmonized between datasets.

- coderdata/dataset.yml
Updated dataset.yml so it is ready for the package. This includes dropping ctpac and  mpnstpdx, renaming datasets as needed, and adding colorectal, liver, and novartis.
> Updated dataset.yml.
